#!/usr/bin/python
# Script for converting results output by Fedra + Fedx with Parallel Bound Join algorithm into csv format
# Authors : Naixin Wang & Thomas Minier
import json
import csv

# load the config
with open("config.json") as configFile:
	config = json.load(configFile)

for setupName, files in config["outputs"].items():
	for name, filepath in files.items():
		# extract the datas generated by the setup
		with open(filepath, "r") as outputSetup:
			# open the csv writer and write the header
			with open(config["outputs_csv"][setupName][name], "w", newline="") as csvfile:
				csvwriter = csv.writer(csvfile, delimiter=";", quotechar="|", quoting=csv.QUOTE_MINIMAL)
				csvwriter.writerow(["Query name", "Query execution time (s)", "Percentage of the CPU used",
				"Average resident set size of the process (kb)", "Maximum resident set size of the process (kb)",
				"Completeness (%)", "Soundness (%)", "Number of selected sources", "Number of selected sources",
				"Shape of the query", "Number of transferred tuples", "Number of calls sent to the endpoints"])
				# convert the results in csv format
				for line in outputSetup:
					csvwriter.writerow([token.rstrip() for token in line.split(" ")])
